/**
 * Emits conformance vectors from the TypeScript implementations that already
 * have tests, so the Kotlin and Swift ports can be checked against behaviour
 * that is known-good rather than against a prose description.
 */
import { writeFileSync } from "node:fs";

import { createRequire } from "node:module";

import * as wire from "../dist/src/wire.js";

// The backend builds to CommonJS; createRequire is the clean way in from ESM.
const require = createRequire(import.meta.url);
const { compile, hashDomain, lookupCompiled } = require("../backend/dist/blocklist/compiled.js");

const BLOCKED = ["pornhub.com", "xvideos.com", "bet365.com", "example-adult-site.test"];

// --- hashes -----------------------------------------------------------------
const hashes = ["", "a", "foobar", "pornhub.com", "www.pornhub.com", "com"].map((input) => ({
  input,
  fnv1a64: hashDomain(input).toString(16).padStart(16, "0"),
}));

// --- a compiled artifact, and what it must answer ---------------------------
const artifact = compile(BLOCKED);
const lookups = [
  "pornhub.com", "www.pornhub.com", "media.cdn.pornhub.com",
  "notpornhub.com", "pornhub.com.evil.test", "PoRnHuB.CoM", "pornhub.com.",
  "bet365.com", "github.com",
].map((domain) => ({ domain, blocked: lookupCompiled(artifact, domain) }));

// --- DNS: a real query, and the sinkhole the resolver answers with ----------
function vectorFor(name, qtype) {
  const { packet } = wire.buildQuery(name, qtype, { txid: 0x1234, edns: true });
  const query = wire.parseQuery(packet);
  return {
    name,
    qtype,
    query: packet.toString("hex"),
    parsed: { txid: query.txid, name: query.name, qtype: query.qtype, qclass: query.qclass },
    sinkhole: wire.buildSinkhole(query, packet, "0.0.0.0", "::", 60).toString("hex"),
  };
}

const dns = [
  vectorFor("pornhub.com", wire.TYPE_A),
  vectorFor("www.pornhub.com", wire.TYPE_A),
  vectorFor("pornhub.com", wire.TYPE_AAAA),
  // HTTPS/SVCB must come back NODATA or its ipv4hint routes around the sinkhole.
  vectorFor("pornhub.com", wire.TYPE_HTTPS),
];

const out = {
  $comment:
    "Generated by scripts-gen-vectors.mjs from the TypeScript implementations in " +
    "src/wire.ts and backend/src/blocklist/compiled.ts, both of which have test " +
    "suites. A Kotlin or Swift port MUST reproduce every value here exactly. " +
    "Regenerate rather than hand-edit.",
  generatedAt: new Date().toISOString(),
  compiledArtifact: {
    domains: BLOCKED,
    hex: artifact.toString("hex"),
    header: { magic: "AEGB", version: 1, hashId: 1, count: artifact.readUInt32LE(8) },
  },
  hashes,
  lookups,
  dns,
};

// Two destinations, written together so they cannot drift: one for humans and
// the Swift port to read, one on the JVM test classpath.
const targets = [
  "../mobile/modules/aegis-filter/conformance/vectors.json",
  "../mobile/modules/aegis-filter/android/src/test/resources/conformance-vectors.json",
];
const body = `${JSON.stringify(out, null, 2)}\n`;
for (const target of targets) writeFileSync(new URL(target, import.meta.url), body);
console.log(`wrote ${targets.length} copies of the vectors`);
console.log(`  ${hashes.length} hash vectors, ${lookups.length} lookups, ${dns.length} DNS pairs`);
console.log(`  artifact: ${artifact.length} bytes, ${artifact.readUInt32LE(8)} domains`);
